// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM9S7fGeHcpO0-7sPceRDZD-GSdtrE8QI',
    appId: '1:828016466157:web:ddafe65059de87700214e4',
    messagingSenderId: '828016466157',
    projectId: 'students-492f4',
    authDomain: 'students-492f4.firebaseapp.com',
    databaseURL: 'https://students-492f4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'students-492f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAM4acZox3GaVuYUkcoJcPDaNd5q-Rc2s',
    appId: '1:828016466157:android:4c743509351f91640214e4',
    messagingSenderId: '828016466157',
    projectId: 'students-492f4',
    databaseURL: 'https://students-492f4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'students-492f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAemQorbOq6HCbQxL5aZYLALtul9aFXTpo',
    appId: '1:828016466157:ios:5c95d3b5f18469380214e4',
    messagingSenderId: '828016466157',
    projectId: 'students-492f4',
    databaseURL: 'https://students-492f4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'students-492f4.firebasestorage.app',
    iosBundleId: 'com.example.seliukovVadimKiuki219',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAemQorbOq6HCbQxL5aZYLALtul9aFXTpo',
    appId: '1:828016466157:ios:5c95d3b5f18469380214e4',
    messagingSenderId: '828016466157',
    projectId: 'students-492f4',
    databaseURL: 'https://students-492f4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'students-492f4.firebasestorage.app',
    iosBundleId: 'com.example.seliukovVadimKiuki219',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM9S7fGeHcpO0-7sPceRDZD-GSdtrE8QI',
    appId: '1:828016466157:web:aecdba77c54f76fa0214e4',
    messagingSenderId: '828016466157',
    projectId: 'students-492f4',
    authDomain: 'students-492f4.firebaseapp.com',
    databaseURL: 'https://students-492f4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'students-492f4.firebasestorage.app',
  );
}
